# Generated by Django 4.2.14 on 2025-01-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='Password',
            field=models.CharField(max_length=500),
        ),
    ]
